# Generated by Django 4.2.13 on 2024-06-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcompbizproc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BizprocModel',
            new_name='BusinessProcessModel',
        ),
        migrations.AlterModelTable(
            name='businessprocessmodel',
            table='business_processes',
        ),
    ]
