# Generated by Django 4.2.13 on 2024-06-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allcompbizproc', '0002_rename_bizprocmodel_businessprocessmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprocessmodel',
            old_name='process_name',
            new_name='name',
        ),
    ]
