# Generated by Django 4.2.13 on 2024-06-13 14:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
            ],
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
