# Generated by Django 4.2.13 on 2024-06-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_data_in_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
