# Generated by Django 4.2.13 on 2024-06-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallInfo',
            new_name='TelephonyCallInfo',
        ),
    ]
