# Generated by Django 4.2.13 on 2024-06-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls_registration', '0002_rename_callinfo_telephonycallinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephonycallinfo',
            name='messages',
        ),
        migrations.AddField(
            model_name='telephonycallinfo',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telephonycallinfo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rings/'),
        ),
    ]
